config/routes.rb
Rails.application.routes.draw do

  get '/movies/search', to: 'movies#search'
  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:new, :create, :destroy]
  root to: 'movies#index'
  namespace 'admin' do
    resources :users
    resource :shadow_sessions, only: [:new, :create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

  def search
    @movies = Movie.all

    @movies = @movies.search(params[:search_query]) unless params[:search_query].blank?
    @movies = @movies.duration_within(params[:min_runtime_in_minutes],params[:max_runtime_in_minutes]) unless params[:max_runtime_in_minutes].blank? && params[:min_runtime_in_minutes].blank?
    render :index
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(:title, :release_date, :director, :poster_image, :runtime_in_minutes, :description)
  end
  
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

  def shortened(string_in, maxlength)
    return string_in if maxlength < 5
    unless string_in.length <= maxlength
      string_in[0,maxlength-2] << "…"
    else
      string_in
    end
  end

end

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>

  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

<%= form_for @movie do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>
  <div>
    <%= f.label :poster_image %><br>
    <%= f.file_field :poster_image %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/movies/_movie_display.html.erb
<% movie_left, movie_right = movie_pair %>
<div class="movie-holder-outer left col-md-6 col-sm-12" data-color="#<%= movie_left.color.to_s(16) %>">
  <div class="movie-holder-inner left">
    <div class="row">
      <div class="col-md-5 col-sm-5 col-xs-12 image-holder">
        <% if movie_left.poster_image && movie_left.poster_image.thumb.url %>
          <%= link_to image_tag(movie_left.poster_image.url), movie_path(movie_left) %>
        <% else %>
          <img src="/thumb_movie-poster-template.jpg"/>
        <% end %>
      </div>

      <div class="col-md-7 col-sm-7 col-xs-12 info-holder">
        <h2><%= link_to shortened(movie_left.title, 35), movie_path(movie_left), title: movie_left.title %></h2>
        <h3><%= movie_left.release_date.strftime("%b %Y") %></h3>
        <h4>Dir. <%= shortened(movie_left.director,20) %> | <%= movie_left.runtime_in_minutes %> minutes</h4>
        <p title="<%= movie_left.description %>"><%= shortened(movie_left.description,180) %></p>
        <p><small><%= movie_left.reviews.count %> reviews. Average rating: <%= movie_left.review_average %></small></p>
      </div>
    </div>
  </div>
</div>

<% if movie_right %>
<div class="movie-holder-outer right col-md-6 col-sm-12" data-color="#<%= movie_right.color.to_s(16) %>">
  <div class="movie-holder-inner right">
    <div class="row">
      <div class="col-md-7 col-sm-7 col-xs-12 info-holder">
        <h2><%= link_to shortened(movie_right.title, 35), movie_path(movie_right), title: movie_right.title %></h2>
        <h3><%= movie_right.release_date.strftime("%b %Y") %></h3>
        <h4>Dir. <%= shortened(movie_right.director,20) %> | <%= movie_right.runtime_in_minutes %> minutes</h4>
        <p title="<%= movie_right.description %>"><%= shortened(movie_right.description,180) %></p>
        <p><small><%= movie_right.reviews.count %> reviews. Average rating: <%= movie_right.review_average %></small></p>
      </div>

      <div class="col-md-5 col-sm-5 col-xs-12 image-holder">
        <% if movie_right.poster_image && movie_right.poster_image.thumb.url %>
          <%= link_to image_tag(movie_right.poster_image.url), movie_path(movie_right) %>
        <% else %>
          <img src="/thumb_movie-poster-template.jpg"/>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/movies/_new_movie_display.html.erb
<div class="movie-holder-outer right col-md-6 col-sm-12">
  <div class="movie-holder-inner right">
    <div class="row">
      <div class="col-md-7 sm-7 xs-12 info-holder">
        <h2><%= link_to "Submit a Movie!", new_movie_path %></h2>
        <h3>Month Year</h3>
        <h4>Dir. Blargh</h4>
        <p>hi i am a movie description! todo: match this to movie display partial later!</p>
      </div>

      <div class="col-md-5 sm-5 xs-12 image-holder">
        <%= link_to image_tag("/movie-poster-template.jpg"), new_movie_path %>
      </div>
    </div>
  </div>
</div>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>

<%= render 'form' %>

app/views/movies/index.html.erb
<main class="container-fluid">
  <% rendered = false %>
  <% @movies.each_slice(2) do |movie_pair| %>
    <div class="row movie-pair">
      <%= render partial: "movie_display", locals: {movie_pair: movie_pair} %>
      <% unless movie_pair[1] %>
        <% rendered = true %>
        <%= render partial: "new_movie_display" %>
      <% end %>
    </div>
  <% end %>
  <% unless rendered %>
    <div class="row movie-pair">
        <div class="movie-holder-outer left col-md-6 col-sm-12">
          <div class="movie-holder-inner left">
          </div>
        </div>
      <%= render partial: "new_movie_display" %>
    </div>
  <% end %>

</main>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>

<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>
<% if @movie.poster_image && @movie.poster_image.url %>
<%= link_to image_tag(@movie.poster_image.url), movie_path(@movie) %>
<% end %>
<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
<h3><%= @movie.release_date %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
    <% @movie.reviews.each do |review| %>
      <p><%= review.text %></p>
      <p><%= review.rating_out_of_ten %>/10</p>
      <small>- <%= link_to review.user.full_name, user_path(review.user) %></small><br/>
    <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_sessions_path %> to see reviews and add your own.</p> 
<% end %>