config/routes.rb
Rails.application.routes.draw do

  get '/movies/search', to: 'movies#search'
  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:new, :create, :destroy]
  root to: 'movies#index'
  namespace 'admin' do
    resources :users
    resource :shadow_sessions, only: [:new, :create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  
  has_secure_password

  validates :email,
    presence: true, uniqueness: true
  validates :firstname,
    presence: true
  validates :lastname,
    presence: true
  validates :password,
    length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :restrict_to_admin

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      UserMailer.deletion_email(@user).deliver_later
    else
    end
    redirect_to admin_users_path
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "User #{@user.email} created."
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :admin, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented this user from being submitted:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<%= form_for [:admin, @user] do |f| %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :admin %><br>
    <%= f.text_field :admin %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<%= link_to "Back to this user", admin_user_path(@user) %>

<h2>Edit this user.</h2>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>All Users</h1>
<%= link_to "Create new", new_admin_user_path %>

<% @users.each do |user| %>

  <a href=<%=admin_user_path(user)%>><h1><%= user.email %></h1></a>

<% end %>

app/views/admin/users/new.html.erb
<%= link_to "Back to all users", admin_users_path %>

<h2>Enter new user details</h2>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<%= link_to "Back to all users", admin_users_path %><br/>
<h2>User 
  <%= @user.id %>
  (<%= link_to "edit", edit_admin_user_path(@user) %>, 
  <%= link_to "delete", admin_user_path(@user), method: :delete, confirm: "You sure?" %><% unless @user.id == session[:user_id] %>, <%= link_to "shadow", admin_shadow_sessions_path(user_id: @user.id), method: :post %><% end %>)
</h2>
<p>Email: <%= @user.email %></p>
<p>First name: <%= @user.firstname %></p>
<p>Last name: <%= @user.lastname %></p>
<p>Admin: <%= @user.admin ? "Yes" : "No" %></p>
<p>User since: <%= @user.created_at %></p>