config/routes.rb
Rails.application.routes.draw do

  get '/movies/search', to: 'movies#search'
  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:new, :create, :destroy]
  root to: 'movies#index'
  namespace 'admin' do
    resources :users
    resource :shadow_sessions, only: [:new, :create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %>.
      <% unless shadow_user %>
        (<%= link_to "Log out", sessions_path, method: :delete %>)
      <% else %>
        Shadowing from account <%= shadow_user.full_name %> (<%= link_to "Exit shadow mode", admin_shadow_sessions_path, method: :delete %>)
      <% end %>
      <% if current_user.admin %>
        <%= link_to "Admin", admin_users_path %>
      <% end %>
    <% else %>
      <%= link_to "Log In", new_sessions_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path %>>Rotten Mangoes</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%=new_movie_path%>">Submit</a></li>
        <li><a href="#">Profile</a></li>
      </ul>
      <%= form_tag(movies_search_path, method: "get", class: "navbar-form navbar-right", role: "search") do %>
        <div class="form-group">
          <%= label_tag :search_query, "Keyword:" %>
          <%= text_field_tag :search_query, "", class: "form-control", placeholder: "Titanic" %>
        </div>
        <div class="form-group">
          <%= label_tag(:min_runtime_in_minutes, "Running time within:") %>
          <%= number_field_tag :min_runtime_in_minutes, "", class: "form-control duration-search", placeholder: "Minimum" %>
        </div>
        <div class="form-group">
          <%= number_field_tag :max_runtime_in_minutes, "", class: "form-control duration-search", placeholder: "Maximum" %>
        </div>
        <%= submit_tag "Search", class: "btn btn-default" %>
      <% end %>
    </div>
    <!-- /.navbar-collapse -->

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>